flasher_pnotify:
    scripts:
        cdn:
            - 'https://cdn.jsdelivr.net/npm/@flasher/flasher-pnotify@1.3.0/dist/flasher-pnotify.min.js'
        local:
            - '/vendor/flasher/flasher-pnotify.min.js'

    styles:
        cdn:
            - 'https://cdn.jsdelivr.net/npm/@flasher/flasher-pnotify@1.3.0/dist/flasher-pnotify.min.css'
        local:
            - '/vendor/flasher/flasher-pnotify.min.css'
